import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Nav from "@/components/Nav";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex shadow-lg h-full  xl:h-full ">
            <div className="w-2/12 h-full">
              <SideBar />
            </div>
            <div className="w-10/12 h-full">
            <Nav />
              
              {children}
              </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
